### ISSUE TITLE
Event listener factory 'event-logger' is not registered

### ISSUE THREAD

**Issue by epiekarski** [jefflester/minitrino#51]
Around version 407 (perhaps earlier), users will receive the below error thrown by the event-listener when attempting to spin up the event-logger module:

`2023-04-05T17:45:46.345Z	ERROR	main	io.trino.server.Server	Event listener factory 'event-logger' is not registered. Available factories: [immuta-event-listener, starburst-atlas, starburst-open-lineage, http, mysql, audit-log]
java.lang.IllegalArgumentException: Event listener factory 'event-logger' is not registered. Available factories: [immuta-event-listener, starburst-atlas, starburst-open-lineage, http, mysql, audit-log]
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:435)
	at io.trino.eventlistener.EventListenerManager.createEventListener(EventListenerManager.java:114)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Collections$2.tryAdvance(Collections.java:4853)
	at java.base/java.util.Collections$2.forEachRemaining(Collections.java:4861)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at io.trino.eventlistener.EventListenerManager.configuredEventListeners(EventListenerManager.java:101)
	at io.trino.eventlistener.EventListenerManager.loadEventListeners(EventListenerManager.java:86)
	at io.trino.server.Server.doStart(Server.java:162)
	at io.trino.server.Server.lambda$start$0(Server.java:89)
	at io.trino.$gen.Trino_407_e_1____20230405_174525_1.run(Unknown Source)
	at io.trino.server.Server.start(Server.java:89)
	at com.starburstdata.presto.StarburstTrinoServer.main(StarburstTrinoServer.java:46)`

Temporary workaround is to comment out the event-listener.properties volume from the event-logger.yaml all together.

Related Slack: https://starburstdata.slack.com/archives/C01394KHSAU/p1671822000765579

**Comment by jefflester** [comment]
Thanks for filing this @epiekarski! We'll get it addressed in the latest update.

**Comment by jefflester** [comment]
@epiekarski once we release 2.0.3, you will have a working query logger by deploying the Insights module:

```
minitrino provision -m insights
```

It should come out tomorrow or Monday. :)

**Comment by epiekarski** [comment]
@jefflester  Awesome, thanks for the update!!

**Comment by jefflester** [comment]
Closed with #56
